# Translations template for invenio-records-resources.
# Copyright (C) 2025 CERN
# This file is distributed under the same license as the
# invenio-records-resources project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
# 
# Translators:
# Tibor Simko <tibor.simko@cern.ch>, 2025
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: invenio-records-resources 8.3.0\n"
"Report-Msgid-Bugs-To: info@inveniosoftware.org\n"
"POT-Creation-Date: 2025-07-08 19:50+0000\n"
"PO-Revision-Date: 2024-03-21 15:18+0000\n"
"Last-Translator: Tibor Simko <tibor.simko@cern.ch>, 2025\n"
"Language-Team: Persian (https://app.transifex.com/inveniosoftware/teams/23537/fa/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"
"Language: fa\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: invenio_records_resources/records/systemfields/entity_reference.py:46
#, python-format
msgid "Invalid reference for '%(key)s': %(obj)s"
msgstr ""

#: invenio_records_resources/resources/errors.py:73
#: invenio_records_resources/resources/errors.py:74
msgid "Invalid query string syntax."
msgstr ""

#: invenio_records_resources/resources/errors.py:75
msgid "Misconfigured search."
msgstr ""

#: invenio_records_resources/resources/errors.py:86
msgid "Internal server error"
msgstr ""

#: invenio_records_resources/resources/errors.py:135
msgid "Invalid querystring parameters."
msgstr ""

#: invenio_records_resources/resources/errors.py:141
#: invenio_records_resources/resources/errors.py:147
#: invenio_records_resources/services/errors.py:36
msgid "Permission denied."
msgstr ""

#: invenio_records_resources/resources/errors.py:153
msgid "The record has been deleted."
msgstr "رکورد حذف شده است."

#: invenio_records_resources/resources/errors.py:159
msgid "The persistent identifier is already registered."
msgstr ""

#: invenio_records_resources/resources/errors.py:165
msgid "The persistent identifier does not exist."
msgstr ""

#: invenio_records_resources/resources/errors.py:171
msgid "The persistent identifier is not registered."
msgstr ""

#: invenio_records_resources/resources/errors.py:178
msgid "Not found."
msgstr ""

#: invenio_records_resources/resources/errors.py:185
#, python-format
msgid "Facet %(vocabulary_id)s not found."
msgstr ""

#: invenio_records_resources/resources/errors.py:198
msgid "Unable to decode JSON data in request body."
msgstr ""

#: invenio_records_resources/resources/errors.py:204
#: invenio_records_resources/resources/errors.py:210
msgid "Not a valid value."
msgstr ""

#: invenio_records_resources/resources/errors.py:219
msgid "The file upload transfer failed, please try again."
msgstr ""

#: invenio_records_resources/resources/errors.py:226
msgid ""
"Uploading selected files will result in exceeding the max amount per record."
msgstr ""

#: invenio_records_resources/services/errors.py:51
#, python-format
msgid ""
"Revision id provided(%(expected_revision_id)s) doesn't match record's "
"one(%(record_revision_id)s)"
msgstr ""

#: invenio_records_resources/services/errors.py:87
#, python-format
msgid "Facet %(vocab)s not found."
msgstr ""

#: invenio_records_resources/services/errors.py:97
#, python-format
msgid "Record '%(recid)s' has no file '%(file_key)s'."
msgstr ""

#: invenio_records_resources/services/errors.py:113
#, python-format
msgid "Record '%(recid)s' failed to upload file '%(file_key)s'."
msgstr ""

#: invenio_records_resources/services/errors.py:130
#, python-brace-format
msgid ""
"Uploading the selected files would result in {files_count} files (max is "
"{max_files})."
msgstr ""

#: invenio_records_resources/services/custom_fields/errors.py:37
#, python-format
msgid ""
"Namespace %(given_namespace)s is not valid for custom field %(field_name)s."
msgstr ""

#: invenio_records_resources/services/custom_fields/errors.py:54
#, python-format
msgid "Custom fields %(field_names)s are not configured."
msgstr ""

#: invenio_records_resources/services/custom_fields/errors.py:70
#, python-format
msgid "Invalid argument %(arg_name)s passed when initializing custom field."
msgstr ""

#: invenio_records_resources/services/files/service.py:318
msgid "File upload transfer failed."
msgstr ""

#: invenio_records_resources/services/files/components/metadata.py:83
msgid "Empty files are not accepted."
msgstr ""

#: invenio_records_resources/services/files/transfer/base.py:92
msgid "File size limit exceeded."
msgstr ""

#: invenio_records_resources/services/records/config.py:35
msgid "Best match"
msgstr ""

#: invenio_records_resources/services/records/config.py:39
msgid "Newest"
msgstr ""

#: invenio_records_resources/services/records/config.py:43
msgid "Oldest"
msgstr ""

#: invenio_records_resources/services/records/components/files.py:89
msgid "You must first delete all files to set the record to be metadata-only."
msgstr ""

#: invenio_records_resources/services/records/params/pagination.py:39
msgid "Invalid pagination parameters."
msgstr ""

#: invenio_records_resources/services/records/params/querystr.py:30
msgid "You cannot specify both 'q' and 'suggest' parameters at the same time."
msgstr ""

#: invenio_records_resources/services/records/params/querystr.py:41
msgid "Invalid 'suggest' parameter."
msgstr ""

#: invenio_records_resources/services/records/params/sort.py:62
#, python-format
msgid "Invalid sort option '%(sort_option)s'."
msgstr ""

#: invenio_records_resources/services/records/queryparser/transformer.py:128
#: invenio_records_resources/services/records/queryparser/transformer.py:133
#, python-format
msgid "Invalid search field: %(field_name)s."
msgstr ""
