# Translations template for invenio-records-resources.
# Copyright (C) 2025 CERN
# This file is distributed under the same license as the
# invenio-records-resources project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
# 
# Translators:
# Alizee Pace <alizee.pace@gmail.com>, 2024
# Tibor Simko <tibor.simko@cern.ch>, 2025
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: invenio-records-resources 5.10.1\n"
"Report-Msgid-Bugs-To: info@inveniosoftware.org\n"
"POT-Creation-Date: 2025-04-01 13:38+0000\n"
"PO-Revision-Date: 2024-03-21 15:18+0000\n"
"Last-Translator: Tibor Simko <tibor.simko@cern.ch>, 2025\n"
"Language-Team: Italian (https://app.transifex.com/inveniosoftware/teams/23537/it/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"
"Language: it\n"
"Plural-Forms: nplurals=3; plural=n == 1 ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;\n"

#: invenio_records_resources/records/systemfields/entity_reference.py:46
#, python-format
msgid "Invalid reference for '%(key)s': %(obj)s"
msgstr ""

#: invenio_records_resources/resources/errors.py:61
#: invenio_records_resources/resources/errors.py:62
msgid "Invalid query string syntax."
msgstr ""

#: invenio_records_resources/resources/errors.py:63
msgid "Misconfigured search."
msgstr ""

#: invenio_records_resources/resources/errors.py:74
msgid "Internal server error"
msgstr "Errore interno del server"

#: invenio_records_resources/resources/errors.py:120
msgid "Invalid querystring parameters."
msgstr ""

#: invenio_records_resources/resources/errors.py:126
#: invenio_records_resources/resources/errors.py:132
#: invenio_records_resources/services/errors.py:36
msgid "Permission denied."
msgstr ""

#: invenio_records_resources/resources/errors.py:138
msgid "The record has been deleted."
msgstr "Il record Ã¨ stato cancellato."

#: invenio_records_resources/resources/errors.py:144
msgid "The persistent identifier is already registered."
msgstr ""

#: invenio_records_resources/resources/errors.py:150
msgid "The persistent identifier does not exist."
msgstr ""

#: invenio_records_resources/resources/errors.py:156
msgid "The persistent identifier is not registered."
msgstr ""

#: invenio_records_resources/resources/errors.py:163
msgid "Not found."
msgstr ""

#: invenio_records_resources/resources/errors.py:170
#, python-format
msgid "Facet %(vocabulary_id)s not found."
msgstr ""

#: invenio_records_resources/resources/errors.py:183
msgid "Unable to decode JSON data in request body."
msgstr ""

#: invenio_records_resources/resources/errors.py:189
#: invenio_records_resources/resources/errors.py:195
msgid "Not a valid value."
msgstr ""

#: invenio_records_resources/resources/errors.py:204
msgid "The file upload transfer failed, please try again."
msgstr ""

#: invenio_records_resources/resources/errors.py:211
msgid ""
"Uploading selected files will result in exceeding the max amount per record."
msgstr ""

#: invenio_records_resources/services/errors.py:51
#, python-format
msgid ""
"Revision id provided(%(expected_revision_id)s) doesn't match record's "
"one(%(record_revision_id)s)"
msgstr ""

#: invenio_records_resources/services/errors.py:73
#, python-format
msgid "Facet %(vocab)s not found."
msgstr ""

#: invenio_records_resources/services/errors.py:83
#, python-format
msgid "Record '%(recid)s' has no file '%(file_key)s'."
msgstr ""

#: invenio_records_resources/services/errors.py:99
#, python-format
msgid "Record '%(recid)s' failed to upload file '%(file_key)s'."
msgstr ""

#: invenio_records_resources/services/errors.py:116
#, python-brace-format
msgid ""
"Uploading the selected files would result in {files_count} files (max is "
"{max_files})."
msgstr ""

#: invenio_records_resources/services/custom_fields/errors.py:37
#, python-format
msgid ""
"Namespace %(given_namespace)s is not valid for custom field %(field_name)s."
msgstr ""

#: invenio_records_resources/services/custom_fields/errors.py:54
#, python-format
msgid "Custom fields %(field_names)s are not configured."
msgstr ""

#: invenio_records_resources/services/custom_fields/errors.py:70
#, python-format
msgid "Invalid argument %(arg_name)s passed when initializing custom field."
msgstr ""

#: invenio_records_resources/services/files/service.py:264
msgid "File upload transfer failed."
msgstr ""

#: invenio_records_resources/services/files/transfer.py:77
msgid "File size limit exceeded."
msgstr ""

#: invenio_records_resources/services/files/transfer.py:103
msgid "Empty files are not accepted."
msgstr ""

#: invenio_records_resources/services/records/config.py:36
msgid "Best match"
msgstr ""

#: invenio_records_resources/services/records/config.py:40
msgid "Newest"
msgstr ""

#: invenio_records_resources/services/records/config.py:44
msgid "Oldest"
msgstr ""

#: invenio_records_resources/services/records/components/files.py:89
msgid "You must first delete all files to set the record to be metadata-only."
msgstr ""

#: invenio_records_resources/services/records/params/pagination.py:39
msgid "Invalid pagination parameters."
msgstr ""

#: invenio_records_resources/services/records/params/querystr.py:31
msgid "You cannot specify both 'q' and 'suggest' parameters at the same time."
msgstr ""

#: invenio_records_resources/services/records/params/querystr.py:42
msgid "Invalid 'suggest' parameter."
msgstr ""

#: invenio_records_resources/services/records/params/sort.py:62
#, python-format
msgid "Invalid sort option '%(sort_option)s'."
msgstr ""

#: invenio_records_resources/services/records/queryparser/transformer.py:67
#, python-format
msgid "Invalid search field: %(field_name)s."
msgstr ""
